FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY ./src /usr/share/nginx/html

EXPOSE 3000

RUN sed -i 's/listen  .*/listen 3000;/g' /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]